r"""Put the Mantle MCP server in front of an editor, in every repo that instructs an agent.

    python agience-build/scripts/mcp_config.py            # report; writes nothing
    python agience-build/scripts/mcp_config.py --write    # write .vscode/mcp.json + fix .gitignore
    python agience-build/scripts/mcp_config.py --check    # exit 1 if any copy drifted (for CI)

## Why a copy per repo, and not one file somewhere

  * **`.code-workspace`** — VS Code does not read MCP config from a workspace file.
  * **one copy in `agience-build`** — that folder is in none of the five views, so a file there
    would never load.
  * **the user profile** — one copy and no credential in any repo, but invisible to review and it
    does not travel with a clone.

So: a copy per repo, generated from the single source below, with `--check` holding them identical.

## The token is NOT written here

The bearer is a credential and this file lands in every target repo. It is referenced as a VS Code
`${input:}`, so VS Code prompts once and stores it in its own secret storage. The node answers
401 to a bare token and 200 to `Bearer <token>`, so the scheme is part of the header and not part
of the input — the same defect this workspace had in `~/.claude.json` until 2026-08-27.

## `.gitignore`

11 of the 19 ignore `.vscode/` outright, which would make these copies untracked — the exact
"configuration a repo cannot restore". Git will not
descend into an excluded directory, so `!.vscode/mcp.json` alone cannot work: the rule is narrowed
to `.vscode/*` first and the negation added after it. Everything else under `.vscode/` stays
ignored, which is the point — this un-ignores one file, not a directory.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

SERVER_NAME = "mantle"
INPUT_ID = "mantle-bearer"

#: The one source. Every copy is this, rendered.
CONFIG = {
    "inputs": [
        {
            "id": INPUT_ID,
            "type": "promptString",
            "password": True,
            "description": (
                "Mantle bearer token for https://mantle.home.agience.ai "
                "(the raw JWT; 'Bearer ' is added for you)"
            ),
        }
    ],
    "servers": {
        SERVER_NAME: {
            "type": "http",
            "url": "https://mantle.home.agience.ai/mcp",
            "headers": {"Authorization": "Bearer ${input:%s}" % INPUT_ID},
        }
    },
}

BANNER = (
    "GENERATED by agience-build/scripts/mcp_config.py -- edit that, not this. "
    "The bearer is a VS Code input, never a literal: this file is tracked in 19 repos."
)


def workspace_root() -> pathlib.Path:
    """The parent of `agience-build`, which is where the repos are.

    ROOT is the PARENT, never this repo. Getting it wrong is
    silent: discovery finds nothing, the table prints empty and the exit code says fine.
    """
    return pathlib.Path(__file__).resolve().parent.parent.parent


#: Repos that instruct an agent and still must NOT carry this file, with the reason each is out.
#:
#: `agience-mantle` refuses it by its own test — `test_the_repo_holds_only_the_database.py::
#: test_no_client_tooling_is_tracked_here`, which failed the moment this script first wrote there:
#: *"Mantle is the standalone database layer. A consumer of its MCP surface — hooks, capture
#: scripts, personas, reduction workers — belongs with the client, not here."* That is right, and it
#: is the sharper statement of what this file is: an MCP client config pointing AT mantle is not
#: part of mantle.
#:
#: Kept as a named list rather than derived, because the derivation would be grepping another
#: repo's test text — a coupling worse than the list. Removing an entry turns mantle's own suite
#: red, which is how this was found in the first place.
EXCLUDED = {
    "agience-mantle": "its own suite forbids tracked client tooling — it IS the server",
    "_archive": "a working tree that is set down, not worked in",
    "_scratch": "the working floor",
}


def targets(root: pathlib.Path) -> list[pathlib.Path]:
    """Every repo in the workspace — the ones carrying a `.git`.

    Derived, never typed. `agience-prism` is a plain directory holding three repos, so a scan of
    top-level directories alone misses `py`/`js`/`c`; `.git` is what marks a repo, wherever it sits.
    Keyed on `.git` because it is the only marker that cannot be deleted while the repo remains one
    — two earlier markers were both removed out from under this function.
    """
    found = []
    for pattern in ("*/.git", "*/*/.git"):
        for path in sorted(root.glob(pattern)):
            repo = path.parent
            rel = repo.relative_to(root)
            if EXCLUDED.keys() & ({rel.as_posix()} | set(rel.parts)):
                continue
            found.append(repo)
    return found


def rendered() -> str:
    doc = {"$comment": BANNER}
    doc.update(CONFIG)
    return json.dumps(doc, indent=2) + "\n"


#: The comment goes on its OWN line. Measured 2026-08-27: `.gitignore` treats `#` as a comment
#: only at the START of a line, so `!.vscode/mcp.json   # why` is one literal pattern containing
#: spaces and a hash — it matches nothing, the `.vscode/*` above it still wins, and
#: `git check-ignore` reported the file ignored in all 14 repos that had been "fixed".
_NARROW = [
    ".vscode/*",
    "# the Mantle MCP server, tracked deliberately -- agience-build/scripts/mcp_config.py",
    "!.vscode/mcp.json",
]


def gitignore_fix(text: str) -> str | None:
    """`.vscode/` narrowed so one file can be tracked, or None when nothing needs doing.

    Idempotent, and it REPAIRS the trailing-comment form as well as the original `.vscode/` — a
    run that already wrote the broken negation must be able to correct itself rather than
    reporting nothing to do.
    """
    lines = text.splitlines()
    out, changed = [], False
    for line in lines:
        stripped = line.strip()
        if stripped in (".vscode/", ".vscode"):
            out.extend(_NARROW)
            changed = True
        elif stripped.startswith("!.vscode/mcp.json") and stripped != "!.vscode/mcp.json":
            # the trailing-comment form this script wrote before the defect was found
            out.append("# the Mantle MCP server, tracked deliberately -- "
                       "agience-build/scripts/mcp_config.py")
            out.append("!.vscode/mcp.json")
            changed = True
        else:
            out.append(line)
    if not changed:
        return None
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true", help="write the copies")
    ap.add_argument("--check", action="store_true", help="exit 1 on any drift")
    args = ap.parse_args()

    root = workspace_root()
    repos = targets(root)
    if not repos:
        print("no git repo found under %s" % root, file=sys.stderr)
        return 2

    want = rendered()
    drift = 0
    print("Mantle MCP config for Copilot — source: %s\n" % pathlib.Path(__file__).name)
    for repo in repos:
        dest = repo / ".vscode" / "mcp.json"
        have = dest.read_text(encoding="utf-8") if dest.exists() else None
        gi = repo / ".gitignore"
        gi_text = gi.read_text(encoding="utf-8") if gi.exists() else ""
        gi_new = gitignore_fix(gi_text)

        state = "same" if have == want else ("drifted" if have is not None else "missing")
        if state != "same":
            drift += 1
        note = "" if gi_new is None else "  (+ .gitignore narrows .vscode/)"
        mark = {"same": "OK ", "drifted": "!! ", "missing": "-- "}[state]
        # relative to ROOT, never `.name`: prism's three legs are `c`/`js`/`py` and print
        # identically to nothing else in the workspace under their own names.
        print("  %s%-24s %-8s%s" % (mark, repo.relative_to(root).as_posix(), state, note))

        if args.write:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(want, encoding="utf-8")
            if gi_new is not None:
                gi.write_text(gi_new, encoding="utf-8")

    print("\n%d repo(s), %d not matching the source" % (len(repos), drift))
    if args.write:
        print("written. VS Code prompts for the bearer once, per workspace, and keeps it in its")
        print("own secret storage — nothing here holds a credential.")
        return 0
    if args.check:
        if drift:
            print("Regenerate with: python agience-build/scripts/mcp_config.py --write")
        return 1 if drift else 0
    print("Run with --write to create them.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
